name: Remove old artifacts

on:
  schedule:
    - cron: '0 5 * * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove artifacts
      uses: c-hive/gha-remove-artifacts@v1.2.0
      with:
        age: '1 day' # '<number> <unit>', e.g. 5 days, 2 years, 90 seconds, parsed by Moment.js
        # Optional inputs
        # skip-tags: true
        skip-recent: 1